# Runs clang-format to format C++ code and then creates a PR to the branch
# that had changes and triggered this action.
#
# Clang-Format Version Update:
# - Previously, we were using clang-format version 13.0.0.
# - The latest available version is 18.0.0, which is now the default in the GitHub action.
# - We explicitly set `clangFormatVersion: 18.0.0` to ensure consistency.
# - Clang-format 17 had known bugs that could cause formatting failures, so we are avoiding auto-updating.
# - Future updates should be reviewed before upgrading to a new major version.
#
# More details:
# - Clang-Format: https://clang.llvm.org/docs/ClangFormat.html
# - Formatting in VS Code: https://code.visualstudio.com/docs/editor/codebasics#_formatting
name: run-clang-format

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  job:
    name: run-clang-format
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    # Format hpp and cpp files under inst/include, src/, and test/gtest
    # We use Google style to format code.
    steps:
    - uses: actions/checkout@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: DoozyX/clang-format-lint-action@v0.20
      with:
        source: './inst/include ./src ./tests/gtest'
        extensions: 'hpp, cpp'
        style: "{BasedOnStyle: Google, SortIncludes: false}"
        inplace: True
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v8
      with:
        commit-message: 'style: run clang format'
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: format-c++-code-${{ github.ref_name }}
        title: 'format C++ code with clang format'
        body: |
          Auto-generated by [run-clang-format.yml][1]
            [1]: https://github.com/NOAA-FIMS/FIMS/blob/main/.github/workflows/run-clang-format.yml