name: Test FIMS User Setup Bash Script

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  test-setup:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Keep running other OS tests if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true # Speeds up Linux installs via binaries

      - name: Run FIMS User Setup Script
        shell: bash
        run: |
          time bash <(curl -sL https://raw.githubusercontent.com/NOAA-FIMS/FIMS/main/setup_fims.sh)

      - name: Verify FIMS Installation
        shell: Rscript {0}
        run: |
          # Verify FIMS is loadable and print version
          if (requireNamespace("FIMS", quietly = TRUE)) {
            message("SUCCESS: FIMS Version ", packageVersion("FIMS"), " is installed.")
          } else {
            stop("CRITICAL: FIMS was not found in .libPaths()")
          }
